const express = require('express');
const cors = require('cors');
const axios = require('axios');
const { parseGS1 } = require('./shared/gs1-utils');

const app = express();

// CORS configuration to allow requests from frontend
app.use(cors({
    origin: process.env.CORS_ORIGIN || '*', // In production, specify your frontend domain
    credentials: true,
    optionsSuccessStatus: 200
}));

app.use(express.json());

// Simple in-memory storage for inspection records (in production, this should be in a database)
let inspections = [];

function gs1DateToJS(gs1Date) {
    if (!gs1Date || gs1Date.length !== 6) return null;
    const year = 2000 + Number(gs1Date.slice(0, 2));
    const month = Number(gs1Date.slice(2, 4)) - 1;
    const day = Number(gs1Date.slice(4, 6));
    return new Date(Date.UTC(year, month, day));
}

/* ------------------ SCAN API ------------------ */
// Validation middleware
function validateScanRequest(req, res, next) {
    const { barcode } = req.body;

    if (!barcode) {
        return res.status(400).json({ result: 'ERROR', notes: 'Barcode missing' });
    }

    if (typeof barcode !== 'string') {
        return res.status(400).json({ result: 'ERROR', notes: 'Barcode must be a string' });
    }

    if (barcode.length > 200) {
        return res.status(400).json({ result: 'ERROR', notes: 'Barcode too long' });
    }

    next();
}

app.post('/scan', validateScanRequest, async (req, res) => {
    try {
        const { barcode } = req.body;
        console.log('Received barcode for scanning:', barcode);
        if (!barcode) {
            return res.status(400).json({ result: 'ERROR', notes: 'Barcode missing' });
        }

        const parsed = parseGS1(barcode);
        console.log('Parsed barcode data:', parsed);

        const serial = parsed['21'];

        if (!serial) {
            console.log('Serial number not found in parsed data');
            return res.status(400).json({ result: 'INVALID', notes: 'Serial number missing' });
        }

        console.log('Extracted serial number:', serial);

        // Validate serial number format (should be numeric)
        if (!/^[0-9]+$/.test(serial)) {
            console.log('Invalid serial number format');
            return res.status(400).json({ result: 'INVALID', notes: 'Invalid serial number format' });
        }

        // Retrieve all information by calling serialization service API
        let serialRecord;
        try {
            console.log('Calling serialization service to validate serial:', serial);

            // Use environment variable for serialization service URL, fallback to internal Docker service name
            const serializationServiceUrl = process.env.SERIALIZATION_SERVICE_URL || `http://serialization:${process.env.PORT_SERIALIZATION || 3001}`;
            // Call serialization service to validate serial number
            const response = await axios.get(`${serializationServiceUrl}/validate/${serial}`);

            if (response.data.valid) {
                serialRecord = {
                    serial: response.data.serial,
                    batch: response.data.batch,
                    expiryDate: response.data.expiryDate,
                    gtin: response.data.gtin
                };
                console.log('Serial validation successful:', serialRecord);
            } else {
                serialRecord = null;
            }
        } catch (err) {
            if (err.response && err.response.status === 404) {
                console.log('Serial not found in serialization service');
                serialRecord = null;
            } else {
                console.error('Error calling serialization service:', err.message);
                return res.status(500).json({ result: 'ERROR', notes: 'Failed to validate serial number' });
            }
        }

        if (!serialRecord) {
            // More detailed error message
            const errorMessage = `Serial '${serial}' not found in database. Please ensure the barcode was generated by the serialization service.`;
            inspections.push({ serial, result: 'INVALID', notes: 'Serial not found', scannedAt: new Date() });
            return res.status(404).json({ result: 'INVALID', notes: errorMessage });
        }

        const batch = serialRecord.batch;
        let expiryDate = new Date(serialRecord.expiryDate);

        // Validate expiry date
        if (expiryDate < new Date()) {
            inspections.push({ serial, result: 'INVALID', notes: 'Product expired', scannedAt: new Date() });
            return res.status(400).json({ result: 'INVALID', notes: 'Product expired' });
        }

        inspections.push({ serial, result: 'VERIFIED', notes: 'All checks passed', scannedAt: new Date() });

        // Update serial status to SCANNED in serialization service
        try {
            await axios.patch(`${serializationServiceUrl}/status/${serial}`, {
                status: 'SCANNED'
            });
        } catch (updateErr) {
            console.error('Failed to update serial status:', updateErr.message);
            // Don't fail the scan if status update fails
        }

        res.json({
            result: 'VERIFIED',
            serial,
            batch,
            expiry: serialRecord.expiryDate,
            notes: 'All checks passed'
        });

    } catch (err) {
        console.error(err);
        res.status(500).json({ result: 'ERROR', notes: 'Internal server error' });
    }
});

app.get('/health', (req, res) => res.send('OK'));

app.listen(process.env.PORT_INSPECTION || 3003, () => {
    console.log(`Inspection Service running on port ${process.env.PORT_INSPECTION || 3003}`);
});